/* Round data for the three quiz-driven games. */

export const STATUS_ROUNDS = [
  { prompt: 'A client requests /api/projects/999 — no project has that id.',
    options: ['400 Bad Request', '404 Not Found', '410 Gone'], answer: 1,
    explain: '404 — the route is fine, the resource just is not there. 410 means it existed and was deliberately removed.' },
  { prompt: 'A request arrives carrying a JWT that expired an hour ago.',
    options: ['401 Unauthorized', '403 Forbidden', '400 Bad Request'], answer: 0,
    explain: '401 — authentication failed. 403 is for a valid identity without permission.' },
  { prompt: 'A logged-in non-admin user hits /api/admin/users.',
    options: ['401 Unauthorized', '405 Method Not Allowed', '403 Forbidden'], answer: 2,
    explain: '403 — we know who they are, they just are not allowed.' },
  { prompt: 'POST /api/projects succeeds and writes a new row.',
    options: ['200 OK', '201 Created', '202 Accepted'], answer: 1,
    explain: '201 with a Location header. 202 means queued, not done.' },
  { prompt: 'DELETE /api/projects/12 succeeds and returns no body.',
    options: ['204 No Content', '200 OK', '410 Gone'], answer: 0,
    explain: '204 — success, deliberately empty body.' },
  { prompt: 'The request body is malformed JSON and cannot be parsed.',
    options: ['422 Unprocessable', '400 Bad Request', '415 Unsupported'], answer: 1,
    explain: '400 — it is not valid syntax. 422 is well-formed but semantically wrong.' },
  { prompt: 'A client blows past your throttle of 100 requests/minute.',
    options: ['503 Unavailable', '429 Too Many Requests', '403 Forbidden'], answer: 1,
    explain: '429, ideally with a Retry-After header.' },
  { prompt: 'Your app is up but Postgres is refusing connections.',
    options: ['500 Internal Server Error', '503 Service Unavailable', '504 Gateway Timeout'], answer: 1,
    explain: '503 — the service cannot handle it right now, and it may recover.' },
]

export const TRACEBACK_ROUNDS = [
  { code: 'Traceback (most recent call last):\n  File "views.py", line 24, in get_project\n    return Response(project.serializer.data)\nAttributeError: \'Project\' object has no\nattribute \'serializer\'',
    prompt: 'What actually fixes this?',
    options: ['Register Project in admin.py',
              'Serialize it: ProjectSerializer(project).data',
              'Import Response from rest_framework.status'], answer: 1,
    explain: 'A model instance has no .serializer — you pass the instance into the serializer class.' },
  { code: 'Traceback (most recent call last):\n  File "models.py", line 15, in Order\n    user = models.ForeignKey(User)\nTypeError: ForeignKey.__init__() missing 1\nrequired positional argument: \'on_delete\'',
    prompt: 'What is missing?',
    options: ['on_delete=models.CASCADE',
              'Change it to a OneToOneField',
              "related_name='orders'"], answer: 0,
    explain: 'Since Django 2.0, on_delete is required on every ForeignKey.' },
  { code: 'django.db.utils.IntegrityError: null value in\ncolumn "email" of relation "auth_user"\nviolates not-null constraint',
    prompt: 'What is the cause?',
    options: ['Migrations are out of date',
              'email needs unique=True',
              'email got no value and the column rejects NULL'], answer: 2,
    explain: 'Either send a value or make the column nullable with null=True/blank=True.' },
  { code: 'Traceback (most recent call last):\n  File "urls.py", line 8, in <module>\n    path("api/", include("api.urls")),\ndjango.core.exceptions.ImproperlyConfigured:\nThe included URLconf does not appear to have\nany patterns in it',
    prompt: 'Most likely cause?',
    options: ['api/urls.py has no urlpatterns list (or it is misspelled)',
              'You need to run migrate first',
              'include() must be imported from django.shortcuts'], answer: 0,
    explain: 'include() looks for a module-level urlpatterns — a typo there produces exactly this.' },
  { code: 'RecursionError: maximum recursion depth\nexceeded while calling a Python object\n  File "models.py", line 31, in save\n    self.save()',
    prompt: 'What went wrong?',
    options: ['Django limits save() depth',
              'save() calls itself instead of super().save()',
              'The model needs a primary key'], answer: 1,
    explain: 'Overriding save() and calling self.save() recurses forever — call super().save(*args, **kwargs).' },
]

export const OUTPUT_ROUNDS = [
  { code: 'print([n * 2 for n in range(4)])',
    prompt: 'What gets printed?',
    options: ['[0, 2, 4, 6]', '[2, 4, 6, 8]', '[0, 1, 2, 3]'], answer: 0,
    explain: 'range(4) is 0..3, each doubled.' },
  { code: 'print(bool([]), bool([0]))',
    prompt: 'What gets printed?',
    options: ['False False', 'False True', 'True True'], answer: 1,
    explain: 'An empty list is falsy; a list containing 0 is still non-empty, so truthy.' },
  { code: 'a = [1, 2, 3]\nb = a\nb.append(4)\nprint(len(a))',
    prompt: 'What gets printed?',
    options: ['3', '4', 'TypeError'], answer: 1,
    explain: 'b is the same list object, not a copy — a is now [1, 2, 3, 4].' },
  { code: 'print("7" + "1")\nprint(7 + 1)',
    prompt: 'What gets printed?',
    options: ['8 then 8', '71 then 8', 'TypeError'], answer: 1,
    explain: 'Strings concatenate; ints add.' },
  { code: 'd = {"a": 1}\nprint(d.get("b", 0))',
    prompt: 'What gets printed?',
    options: ['0', 'None', 'KeyError'], answer: 0,
    explain: '.get() returns the default instead of raising — that is the point of it.' },
  { code: 'print(list(range(5))[::-2])',
    prompt: 'What gets printed?',
    options: ['[4, 2, 0]', '[0, 2, 4]', '[3, 1]'], answer: 0,
    explain: 'Start at the end, step backwards by 2: 4, 2, 0.' },
]
